name: FlakeHub Update & Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *' # 5 AM Daily
  push:
    branches:
      - main
  pull_request:

jobs:
  update-flake-lock:
    name: Update Flake Lock
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@main
      - name: Update Flake Lock
        uses: DeterminateSystems/update-flake-lock@v24
        with:
          pr-title: "chore: update flake.lock"
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}

  check-darwin:
    name: Check Darwin (aarch64-darwin)
    runs-on: macos-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@main

      - name: Setup FlakeHub Cache
        uses: DeterminateSystems/flakehub-cache-action@v2.2.0

      - name: Run flake checks
        run: nix flake check --print-build-logs

  check-linux:
    name: Check Linux (x86_64-linux)
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@main

      - name: Setup FlakeHub Cache
        uses: DeterminateSystems/flakehub-cache-action@v2.2.0

      - name: Run flake checks
        run: nix flake check --print-build-logs
